# Generated by Django 4.2.18 on 2025-01-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
