# Generated by Django 4.2.18 on 2025-04-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('image', '이미지'), ('pdf', 'PDF')], default='image', max_length=10)),
                ('ocr_text', models.TextField(blank=True)),
                ('llm_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OCR 결과',
                'verbose_name_plural': 'OCR 결과',
            },
        ),
    ]
