# Generated by Django 4.2.18 on 2025-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_ocrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='text_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
