# Generated by Django 4.2.18 on 2025-01-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_socialaccount_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='nickname',
        ),
    ]
