# Generated by Django 4.2.18 on 2025-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ocrresult_text_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='analysis_type',
            field=models.CharField(default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='analyze_by_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='llm_response_korean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='translation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='translation_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='translation_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='llm_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
