# Generated by Django 4.2.18 on 2025-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_ocrresult_analysis_type_ocrresult_analyze_by_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrresult',
            options={},
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='file',
            field=models.FileField(upload_to='ocr_files/'),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='ocrresult',
            table='ocr_result',
        ),
    ]
