# Generated by Django 4.2.18 on 2025-06-04 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_ocrresult_options_ocrresult_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_request', models.TextField(verbose_name='원본 요청')),
                ('gpt_suggestion', models.TextField(blank=True, verbose_name='GPT 제안')),
                ('claude_suggestion', models.TextField(blank=True, verbose_name='Claude 제안')),
                ('mixtral_suggestion', models.TextField(blank=True, verbose_name='Mixtral 제안')),
                ('optimized_suggestion', models.TextField(blank=True, verbose_name='최적화된 제안')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='신뢰도 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일정 요청',
                'verbose_name_plural': '일정 요청들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('SCHEDULED', '예정'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='SCHEDULED', max_length=15, verbose_name='상태')),
                ('attendees', models.TextField(blank=True, verbose_name='참석자')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='반복 일정')),
                ('recurring_pattern', models.CharField(blank=True, max_length=50, verbose_name='반복 패턴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정들',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflicting_schedules', models.TextField(verbose_name='충돌 일정들')),
                ('resolution_options', models.TextField(verbose_name='해결 방안들')),
                ('selected_option', models.TextField(blank=True, verbose_name='선택된 방안')),
                ('ai_recommendations', models.TextField(verbose_name='AI 추천 사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '충돌 해결',
                'verbose_name_plural': '충돌 해결들',
                'ordering': ['-created_at'],
            },
        ),
    ]
