# Generated by Django 4.2.18 on 2025-06-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_schedulerequest_schedule_conflictresolution'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conflictresolution',
            table='ConflictResolution',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
        migrations.AlterModelTable(
            name='schedulerequest',
            table='ScheduleRequest',
        ),
    ]
